name: app ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Run Tests
        run: make test

      - name: send fail message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            echo "Displaying failed tests:"
            for file in $(find target/surefire-reports -name '*.txt'); do
              echo "File: $file"
              grep -B 5 -A 10 "FAILURE" $file
            done

      - name: send ok message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"