name: app ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Run Tests
        run: make test

      - name: Collect failed tests
        if: failure()
        id: collect-failed-tests
        run: |
          grep -R "FAILURE" target/surefire-reports/*.txt > failed-tests.txt || true
          if [ -s failed-tests.txt ]; then
            echo "failed_tests<<EOF" >> $GITHUB_OUTPUT
            echo $(cat failed-tests.txt) >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          else
            echo "failed_tests=No failed tests found." >> $GITHUB_OUTPUT
          fi

      - name: send fail message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.collect-failed-tests.outputs.failed_tests }}

      - name: send ok message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"